https://i.redd.it/i2i66ch76zg81.jpg

"""
Fake data factories for development / testing.
Each factory returns a dict (or list of dicts) that mirrors the shape
the real DB queries will eventually return.
Also this file was definitely generated by AI.

Usage:
    from fakeModels import FakeModels
    fake = FakeModels()
    readings = fake.readings(plantID=1, fromDate=0, toDate=time.time(), count=20)
"""

import time
import random
from faker import Faker

fake = Faker()
Faker.seed(0)

# ─── Constants that mirror future DB constraints ─────────────────────────

PLANT_SPECIES = ["Fern", "Cactus", "Succulent", "Orchid", "Spider Plant",
                 "Pothos", "Snake Plant", "Aloe Vera", "Peace Lily", "Basil"]

ROOMS = ["Kitchen", "Living Room", "Bedroom", "Bathroom", "Office", "Balcony"]

STATUSES = ["healthy", "needs attention", "struggling"]

CLIMATES = ["tropical", "arid", "temperate", "continental", "polar"]

TEMP_UNITS = ["Fahrenheit", "Celsius"]


# ─── Factories ────────────────────────────────────────────────────────────

class FakeModels:
    """Central hub for all fake-data generation."""

    # ── Single reading ────────────────────────────────────────────────

    @staticmethod
    def reading(plantID: int = 1, timestamp: float = None) -> dict:
        """One moisture-sensor reading row."""
        return {
            "id": random.randint(1, 100_000),
            "plantId": plantID,
            "moistureLevel": round(random.uniform(10.0, 95.0), 1),
            "timestamp": timestamp or time.time(),
        }

    # ── Multiple readings (for historical data) ──────────────────────

    @staticmethod
    def readings(plantID: int = 1,
                 fromDate: float = 0,
                 toDate: float = None,
                 count: int = 20) -> list[dict]:
        """A time-series of moisture readings between two timestamps."""
        if toDate is None:
            toDate = time.time()
        count = max(2, count)
        data = []
        for i in range(count):
            ts = fromDate + (toDate - fromDate) * i / (count - 1)
            data.append(FakeModels.reading(plantID=plantID, timestamp=int(ts)))
        return data

    # ── Single plant ──────────────────────────────────────────────────

    @staticmethod
    def plant(plantID: int = None,
              plantName: str = None,
              plantRoom: str = None) -> dict:
        """One row from the Plants table."""
        species = random.choice(PLANT_SPECIES)
        return {
            "id": plantID or random.randint(1, 1000),
            "plantName": plantName or fake.first_name() + "'s " + species,
            "plantSpecies": species,
            "mostRecentMoistureLevel": round(random.uniform(10.0, 95.0), 1),
            "room": plantRoom or random.choice(ROOMS),
            "status": random.choice(STATUSES)
            # "plantImage": f"{IMAGE_BASE_PATH}/{species.replace(' ', '_').lower()}.png",
        }

    # ── User ──────────────────────────────────────────────────────────

    @staticmethod
    def user(username: str = None) -> dict:
        """One row from the Users table."""
        return {
            "id": random.randint(1, 10_000),
            "username": username or fake.user_name(),
            "password": fake.password(length=12),
            "tempUnit": random.choice(TEMP_UNITS),
            "climate": random.choice(CLIMATES),
        }
