services:
  backend:
    build:
      context: ..
      dockerfile: docker/Services/Backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    volumes:
      - ..:/repo
    networks:
      - app-network
    
  frontend:
    build:
      context: ..
      dockerfile: docker/Services/Frontend
    expose:
      - "80"
    volumes:
      - ..:/repo
      - frontend_node_modules:/repo/frontend/Vue-Project/node_modules
    networks:
      - app-network

  gitupdater:

    build:
      context: ..
      dockerfile: docker/Services/GitUpdater
    ports:
      - "8500:8500"
    env_file:
      - ../backend/.env
    volumes:
      - ..:/repo
      - /root/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    networks:
      - app-network

  nginx:
    build:
      context: ..
      dockerfile: docker/Services/Nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - backend
      - frontend
      - gitupdater
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    # On first run, use the command below to obtain the certificate:
    #   docker compose -f docker/Server.yaml run --rm --entrypoint "certbot" certbot certonly --webroot -w /var/www/certbot -d uab420.desverreaux.com --agree-tos --email YOUR_EMAIL
    # For renewals, use:
    #   docker compose -f docker/Server.yaml run --rm --entrypoint "certbot" certbot renew
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; done'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
  certbot-etc:
  certbot-var:
  certbot-www: